// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmiypkmnruwpvhorkmud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtaXlwa21ucnV3cHZob3JrbXVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDYyMTYsImV4cCI6MjA2NTU4MjIxNn0.EtxXFxE0Q9NRgVqrXEAVI5LofS-D0geBuWoV_Kiq8Go";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);